=== alepradas/LENMAR-ASIR1/ejercicios/DTD/futbol.dtd
<!ELEMENT futbol (vacio,novacio,equipos)>
    <!ELEMENT vacio EMPTY>
    <!ELEMENT novacio (#PCDATA)>
    <!ELEMENT equipos (equipo)>
       <!ELEMENT equipo (nombre,copas,jugadores,equipacion,partidos,estadio)>
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT copas (#PCDATA)>
            <!ELEMENT jugadores (pichichi)>
                <!ELEMENT pichichi (nombre2,fechaNacimiento,goles,tarjetas)>
                    <!ELEMENT nombre2 (#PCDATA)>
                    <!ELEMENT fechaNacimiento (#PCDATA)>
                    <!ELEMENT goles (#PCDATA)>
                    <!ELEMENT tarjetas (amarillas,rojas)>
                        <!ELEMENT amarillas (#PCDATA)>
                        <!ELEMENT rojas (#PCDATA)>
            <!ELEMENT equipacion (primera,segunda)>
                <!ELEMENT primera (#PCDATA)>
                <!ELEMENT segunda (#PCDATA)>
            <!ELEMENT partidos (jugados)>
                <!ELEMENT jugados (ganados,perdidos,empatados)>
                    <!ELEMENT ganados (#PCDATA)>
                    <!ELEMENT perdidos (#PCDATA)>
                    <!ELEMENT empatados (#PCDATA)>
            <!ELEMENT estadio (nombre3,capacidad)>
                <!ELEMENT nombre3 (#PCDATA)>
                <!ELEMENT capacidad (#PCDATA)>

=== alepradas/LENMAR-ASIR1/ejercicios/DTD/futbol.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE futbol SYSTEM "futbol.dtd">
<futbol>
<vacio/> <!-- Elemento vacío-->
<novacio>novacio</novacio>  <!-- Elemento no vacío-->
    <equipos>
        <equipo>
            <nombre>Betis</nombre>
            <copas>0</copas>
            <jugadores>
                <pichichi>
                    <nombre2>Joaquin</nombre2>
                    <fechaNacimiento>1980-10-10</fechaNacimiento>
                    <goles>100</goles>
                    <tarjetas>
                        <amarillas>1</amarillas>
                        <rojas>0</rojas>
                    </tarjetas>
                </pichichi>
            </jugadores>
            <equipacion>
                <primera>blanco y verde</primera>
                <segunda>azul y blanca</segunda>
            </equipacion>
            <partidos>
                <jugados>
                    <ganados>100</ganados>
                    <perdidos>10</perdidos>
                    <empatados>50</empatados>
                </jugados>
            </partidos>
            <estadio>
                <nombre3>Benito Villamarín</nombre3>
                <capacidad>60000</capacidad>
            </estadio>
        </equipo>
    </equipos>
</futbol>
