=== alepradas/LENMAR-ASIR1/ejercicios/DTD/medicamentos.dtd
<!ELEMENT medicamentos (medicamento+)>
<!ELEMENT medicamento (nombre,administración,dosis)>
<!ELEMENT nombre (genérico,comercial+)>
<!ELEMENT genérico (#PCDATA)>
<!ELEMENT comercial (#PCDATA)>
<!ELEMENT administración (#PCDATA)>
<!ELEMENT dosis (#PCDATA)>

<!-- Atributos -->
<!ATTLIST nombre id CDATA #REQUIRED>
<!ATTLIST administración tipo CDATA #REQUIRED>

=== alepradas/LENMAR-ASIR1/ejercicios/DTD/medicamentos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE medicamentos SYSTEM "medicamentos.dtd">
<medicamentos>
    <medicamento>
        <nombre id="1">
            <genérico></genérico>
            <comercial></comercial>
        </nombre>
        <administración tipo="Intramuscular"></administración>
        <dosis>20 mg</dosis>
    </medicamento>
    <medicamento>
        <nombre id="2">
            <genérico></genérico>
            <comercial></comercial>
        </nombre>
        <administración tipo="Oral"></administración>
        <dosis>10 mg</dosis>
    </medicamento>
    <medicamento>
        <nombre id="3">
            <genérico></genérico>
            <comercial></comercial>
        </nombre>
        <administración tipo="Oral"></administración>
        <dosis>5 mg</dosis>
    </medicamento>
</medicamentos>
