=== alepradas/LENMAR-ASIR1/ejercicios/Validación XML/calendario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="calendario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="trimestre">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="asignatura" minOccurs="1" maxOccurs="6">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="tema" minOccurs="1" maxOccurs="10" />
                                        <xs:element name="fechaExamenes" type="xs:date" maxOccurs="unbounded" />
                                    </xs:sequence>
                                    <xs:attribute name="nombre" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="ciclos" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="tema">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" />
                <xs:element name="notaMedia" minOccurs="2" maxOccurs="10">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="teoria" type="xs:float" />
                            <xs:element name="practica" type="xs:float" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alepradas/LENMAR-ASIR1/ejercicios/Validación XML/calendario.xml
<?xml version="1.0" encoding="UTF-8"?>
<calendario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="calendario.xsd">

    <trimestre ciclos="primero">
        <asignatura nombre="LLMM">
            <tema id="4">
                <nombre>RSS</nombre>
                <notaMedia>
                    <teoria>4.5</teoria>
                    <practica>5.5</practica>
                </notaMedia>
                <notaMedia>
                    <teoria>8</teoria>
                    <practica>9</practica>
                </notaMedia>
            </tema>
            <tema id="5">
                <nombre>RSS</nombre>
                <notaMedia>
                    <teoria>4.5</teoria>
                    <practica>5.5</practica>
                </notaMedia>
                <notaMedia>
                    <teoria>8</teoria>
                    <practica>9</practica>
                </notaMedia>
            </tema>
            <fechaExamenes>2022-02-13</fechaExamenes>
            <fechaExamenes>2022-02-13</fechaExamenes>
            <fechaExamenes>2022-02-13</fechaExamenes>
            <fechaExamenes>2022-02-13</fechaExamenes>
        </asignatura>
        <asignatura nombre="PLAR">
            <tema id="4">
                <nombre>RSS</nombre>
                <notaMedia>
                    <teoria>4.5</teoria>
                    <practica>5.5</practica>
                </notaMedia>
                <notaMedia>
                    <teoria>8</teoria>
                    <practica>9</practica>
                </notaMedia>
            </tema>
            <tema id="5">
                <nombre>RSS</nombre>
                <notaMedia>
                    <teoria>4.5</teoria>
                    <practica>5.5</practica>
                </notaMedia>
                <notaMedia>
                    <teoria>8</teoria>
                    <practica>9</practica>
                </notaMedia>
            </tema>
            <fechaExamenes>2022-02-13</fechaExamenes>
            <fechaExamenes>2022-02-13</fechaExamenes>
            <fechaExamenes>2022-02-13</fechaExamenes>
            <fechaExamenes>2022-02-13</fechaExamenes>
        </asignatura>
    </trimestre>
</calendario>
