=== alepradas/LENMAR-ASIR1/ejercicios/Validación XML/expresiones.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="patrones">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="telefono">
                    <xs:simpleType>
                        <xs:restriction base="xs:string"></xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="password">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:maxLength value="9"></xs:maxLength>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="dni">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]{8}[-][a-zA-Z]" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="expresiones">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="maldito"></xs:enumeration>
                <xs:enumeration value="mala"></xs:enumeration>
                <xs:enumeration value="buenos dias"></xs:enumeration>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="pastilla">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]{8}[-][a-zA-Z]" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="email">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[a-z0-9]+[@][a-z]+[.][a-z]+" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="email2">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[_]*[a-z0-9]{6,50}[@][a-z]{1,10}[.][a-z]{2,6}" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="sexo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="femenino" default="f">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="f|F|M|Mujer"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="masculino" default="m">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="m|M|Hombre|H"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="atributoSexo"></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="atributoSexo">
        <xs:restriction base="xs:string">
            <xs:minInclusive value="0"></xs:minInclusive>
            <xs:maxInclusive value="1"></xs:maxInclusive>
            <!-- Otra manera -->
            <xs:enumeration value="0|1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== alepradas/LENMAR-ASIR1/ejercicios/Validación XML/expresiones.xml
<?xml version="1.0" encoding="UTF-8"?>
<patrones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="expresiones.xsd">
    <telefono>+34566677893</telefono>
    <password></password>
    <dni>47537681Q</dni>
    <expresiones>mala</expresiones>
    <pastilla>viagra</pastilla>
    <email>alepradas.asir@gmail.com</email>
    <email2>_abcdef@a.es</email2>
</patrones>
