=== alepradas/LENMAR-ASIR1/ejercicios/Validación XML/resumen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="resumenes">
    <xs:complexType>
        <xs:sequence>
            <!-- Definimos elementos simples-->
            <xs:element name="ConjuntoSimples">
                <xs:complexType>
                    <!-- Vamos a definir elementos simples-->
                    <xs:all>
                        <xs:element name="SinAtributo" type="xs:string"></xs:element>
                        <!-- Tipo simple: integer, string, date,etc-->
                        <xs:element name="SinAtributoTipoSimple" type="xs:date"></xs:element>
                        <xs:element name="SinAtributoTipoDefinidos" type="direccion"></xs:element>
                        <xs:element name="ConAtributo">   
                        </xs:element>
                    </xs:all>

                </xs:complexType>
            </xs:element>
            <xs:element name="ConjuntoComplejos">
                <xs:complexType>
                    <!-- Vamos a definir elementos complejos-->
                    <xs:all>
                        <!-- Sin atributos con tipos base-->
                        <xs:element name="Elemento1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="subElemento1" type="xs:string"></xs:element>
                                    <xs:element name="subElemento2" type="xs:string"></xs:element>
                                </xs:sequence>
                                <xs:attribute name="id" type="xs:integer"></xs:attribute>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="Elemento2">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="subElemento1" type="xs:string"></xs:element>
                                    <xs:element name="subElemento2" type="xs:integer"></xs:element>
                                </xs:sequence>
                                
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="Elemento3">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="subElemento1" type="xs:ciudad"></xs:element>
                                    <xs:element name="subElemento2" type="xs:direccion"></xs:element>
                                </xs:sequence>
                                
                            </xs:complexType>
                        </xs:element>
                    </xs:all>   
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:element>
<!-- Definicion de tipos-->
<!-- Tipo "Ciudad"-->
<xs:simpleType name="ciudad">
    <xs:restriction base="xs:string">
        <xs:enumeration value="Sevilla"></xs:enumeration>
        <xs:enumeration value="Málaga"></xs:enumeration>
        <xs:enumeration value="Huelva"></xs:enumeration>
        <xs:enumeration value="Córdoba"></xs:enumeration>
    </xs:restriction>
</xs:simpleType>
<xs:complexType name="direccion">
    <xs:sequence>
        <xs:element name="localidad" type="xs:string"/>
        <xs:element name="cp" type="xs:integer"/>
        <xs:element name="ciudad" type="xs:string"/>
        <xs:element name="ciudad2" type="xs:ciudad"/>



    </xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== alepradas/LENMAR-ASIR1/ejercicios/Validación XML/resumen.xml
<?xml version="1.0" encoding="UTF-8"?>

<resumenes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resumen.xsd">
<ConjuntoSimples>
        <!-- Tipos Simples sin Stributos-->

    <SinAtributo>Elemento Simple</SinAtributo>
    <SinAtributoTipoSimple>2020-10-10</SinAtributoTipoSimple>
    <SinAtributoTipoDefinidos>Sevilla</SinAtributoTipoDefinidos>

    <!-- Repetir lo anterior pero con atributos-->
    
</ConjuntoSimples>
<ConjuntoComplejos>

    <Elemento1>
        <subElemento1>Cadena</subElemento1>
        <subElemento2>2</subElemento2>
    </Elemento1>

    <Elemento2 id="0">
        <subElemento1>Cadena</subElemento1>
        <subElemento2>2</subElemento2>
    </Elemento2>
    
    <Elemento3>
        <subElemento1>Sevilla</subElemento1>
        <subElemento2>
            <localidad>Ecija</localidad>
            <CP>41568</CP>
            <ciudad>Cualquier ciudad</ciudad>
        </subElemento2>
    </Elemento3>

</ConjuntoComplejos>
</resumenes>
